<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8wEoxri\Glpi_Kernel_KernelProductionContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8wEoxri/Glpi_Kernel_KernelProductionContainer.php') {
    touch(__DIR__.'/Container8wEoxri.legacy');

    return;
}

if (!\class_exists(Glpi_Kernel_KernelProductionContainer::class, false)) {
    \class_alias(\Container8wEoxri\Glpi_Kernel_KernelProductionContainer::class, Glpi_Kernel_KernelProductionContainer::class, false);
}

return new \Container8wEoxri\Glpi_Kernel_KernelProductionContainer([
    'container.build_hash' => '8wEoxri',
    'container.build_id' => '5ea71d69',
    'container.build_time' => 1775917823,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container8wEoxri');
